export default {
  LOAD_ORDER_SUCCEEDED: "LOAD_ORDER_SUCCEEDED",
  LOAD_ORDER_FAILED: "LOAD_ORDER_FAILED",

  // regular order
  GET_REGULAR_REQUEST: "GET_REGULAR_REQUEST",
  GET_REGULAR_SUCCESS: "GET_REGULAR_SUCCESS",
  GET_REGULAR_FAILED: "GET_REGULAR_FAILED",
  POST_REGULAR_REQUEST: "POST_REGULAR_REQUEST",
  POST_REGULAR_SUCCESS: "POST_REGULAR_SUCCESS",
  POST_REGULAR_FAILED: "POST_REGULAR_FAILED",
  UPDATE_REGULAR_REQUEST: "UPDATE_REGULAR_REQUEST",
  UPDATE_REGULAR_SUCCESS: "UPDATE_REGULAR_SUCCESS",
  UPDATE_REGULAR_FAILED: "UPDATE_REGULAR_FAILED",
  
  // end of lease order
  GET_ENDOFLEASE_REQUEST: "GET_ENDOFLEASE_REQUEST",
  GET_ENDOFLEASE_SUCCESS: "GET_ENDOFLEASE_SUCCESS",
  GET_ENDOFLEASE_FAILED: "GET_ENDOFLEASE_FAILED",
  POST_ENDOFLEASE_REQUEST: "POST_ENDOFLEASE_REQUEST",
  POST_ENDOFLEASE_SUCCESS: "POST_ENDOFLEASE_SUCCESS",
  POST_ENDOFLEASE_FAILED: "POST_ENDOFLEASE_FAILED",

  // * USER LIST ACTION TYPE
  GET_USERS_REQUESTED: "GET_USERS_REQUESTED",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILED: "GET_USERS_FAILED",
  // * EMPLOYEE LIST ACTION TYPE
  GET_EMPLOYEES_REQUESTED: 'GET_EMPLOYEES_REQUESTED',
  GET_EMPLOYEES_SUCCESS: 'GET_EMPLOYEES_SUCCESS',
  GET_EMPLOYEES_FAILED: 'GET_EMPLOYEES_FAILED',

  // employee
  GET_EMPLOYEE_REQUEST: "GET_EMPLOYEE_REQUEST",
  GET_EMPLOYEE_SUCCESS: "GET_EMPLOYEE_SUCCESS",
  GET_EMPLOYEE_FAILED: "GET_EMPLOYEE_FAILED",
  // update employee profile
  UPDATE_EMPLOYEE_REQUEST:"UPDATE_EMPLOYEE_REQUEST",
  UPDATE_EMPLOYEE_SUCCESS:"UPDATE_EMPLOYEE_SUCCESS",
  UPDATE_EMPLOYEE_FAILED:"UPDATE_EMPLOYEE_FAILED",

  // Customer Details
  GET_CUSDETAIL_REQUEST: "GET_CUSDETAIL_REQUEST",
  GET_CUSDETAIL_SUCCESS: "GET_CUSDETAIL_SUCCESS",
  GET_CUSDETAIL_FAILED: "GET_CUSDETAIL_FAILED",
  GET_CUSDETAILTABLE_REQUEST: "GET_CUSDETAILTABLE_REQUEST",
  GET_CUSDETAILTABLE_SUCCESS: "GET_CUSDETAILTABLE_SUCCESS",
  GET_CUSDETAILTABLE_FAILED: "GET_CUSDETAILTABLE_FAILED",

  // Staff Details
  GET_STAFFDETAIL_REQUEST:"GET_STAFFDETAIL_REQUEST",
  GET_STAFFDETAIL_SUCCESS:"GET_STAFFDETAIL_SUCCESS",
  GET_STAFFDETAIL_FAILED:"GET_STAFFDETAIL_FAILED",
  GET_STAFFDETAILTABLE_REQUEST:"GET_STAFFDETAILTABLE_REQUEST",
  GET_STAFFDETAILTABLE_SUCCESS:"GET_STAFFDETAILTABLE_SUCCESS",
  GET_STAFFDETAILTABLE_FAILED:"GET_STAFFDETAILTABLE_FAILED",
  // USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST',
  // USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS',
  // USER_REGISTER_FAIL = 'USER_REGISTER_FAIL',
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',
  USER_SIGNIN_REQUEST: 'USER_SIGNIN_REQUEST',
  USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
  USER_SIGNIN_FAIL: 'USER_SIGNIN_FAIL',
  USER_SIGNOUT_REQUEST: 'USER_SIGNOUT_REQUEST',
  USER_SIGNOUT: 'USER_SIGNOUT',

  EMPLOYEE_REGISTER_REQUEST: 'EMPLOYEE_REGISTER_REQUEST',
  EMPLOYEE_REGISTER_SUCCESS: 'EMPLOYEE_REGISTER_SUCCESS',
  EMPLOYEE_REGISTER_FAIL: 'EMPLOYEE_REGISTER_FAIL',
  EMPLOYEE_SIGNIN_REQUEST: 'EMPLOYEE_SIGNIN_REQUEST',
  EMPLOYEE_SIGNIN_SUCCESS: 'EMPLOYEE_SIGNIN_SUCCESS',
  EMPLOYEE_SIGNIN_FAIL: 'EMPLOYEE_SIGNIN_FAIL',
  EMPLOYEE_SIGNOUT_REQUEST: 'EMPLOYEE_SIGNOUT_REQUEST',
  EMPLOYEE_SIGNOUT: 'EMPLOYEE_SIGNOUT',

  // GET_COMPLETE_REQUEST:"GET_COMPLETE_REQUEST",
  // GET_COMPLETE_SUCCESS:"GET_COMPLETE_SUCCESS",
  // GET_COMPLETE_FAILED:"GET_COMPLETE_FAILED",

  // All Orders
  GET_ALL_ORDERS_REQUESTED: 'GET_ALL_ORDERS_REQUESTED',
  GET_ALL_ORDERS_SUCCESS: 'GET_ALL_ORDERS_SUCCESS',
  GET_ALL_ORDERS_FAILED: 'GET_ALL_ORDERS_FAILED'
}
