export default {
    LOAD_ORDER_SUCCEEDED: "LOAD_ORDER_SUCCEEDED",
    LOAD_ORDER_FAILED: "LOAD_ORDER_FAILED",
    // regular order
    GET_REGULAR_REQUEST:"GET_REGULAR_REQUEST",
    GET_REGULAR_SUCCESS:"GET_REGULAR_SUCCESS",
    GET_REGULAR_FAILED:"GET_REGULAR_FAILED",
    POST_REGULAR_REQUEST: "POST_REGULAR_REQUEST",
    POST_REGULAR_SUCCESS: "POST_REGULAR_SUCCESS",
    POST_REGULAR_FAILED: "POST_REGULAR_FAILED",
    // * USER LIST ACTION TYPE
    GET_USERS_REQUESTED: "GET_USERS_REQUESTED",
    GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
    GET_USERS_FAILED: "GET_USERS_FAILED",

    USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL = 'USER_REGISTER_FAIL',

    USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST',
    USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS',
    USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL',
    USER_SIGNOUT = 'USER_SIGNOUT',

}