export default {
    LOAD_ORDER_SUCCEEDED: "LOAD_ORDER_SUCCEEDED",
    LOAD_ORDER_FAILED: "LOAD_ORDER_FAILED",

    // regular order
    GET_REGULAR_REQUEST:"GET_REGULAR_REQUEST",
    GET_REGULAR_SUCCESS:"GET_REGULAR_SUCCESS",
    GET_REGULAR_FAILED:"GET_REGULAR_FAILED",
    
    POST_REGULAR_REQUEST:"POST_REGULAR_REQUEST",
    POST_REGULAR_SUCCESS:"POST_REGULAR_SUCCESS",
    POST_REGULAR_FAILED:"POST_REGULAR_FAILED"
    //




}